### ISSUE TITLE
SSL Problem

### ISSUE THREAD

**Issue by tiaanstals** [tokenio/sdk-java#387]
I have got the SDK working on my local machine, but after I build my application there appears to be some initialisation error on the Member Loading phase

`java.lang.RuntimeException: javax.net.ssl.SSLHandshakeException: General OpenSslEngine problem
	at io.reactivex.internal.util.ExceptionHelper.wrapOrThrow(ExceptionHelper.java:45)
	at io.reactivex.internal.observers.BlockingMultiObserver.blockingGet(BlockingMultiObserver.java:91)
	at io.reactivex.Maybe.blockingGet(Maybe.java:2008)
	at io.reactivex.Observable.blockingSingle(Observable.java:4975)
	at io.token.tpp.TokenClient.getMemberBlocking(TokenClient.java:272)
	at com.stack.stackCore.core.service.fundService.v3.TokenIoService.loadMember(TokenIoService.java:322)
	at com.stack.stackCore.core.service.fundService.v3.TokenIoService.lambda$initializeMember$2(TokenIoService.java:393)`

- I have included the SDK in my gradle build, and the build works successfully.
- I generated the keys directory on my machine and they have been placed on the server and appear to be getting fetched correctly

Any help would be appreciated.

**Comment by tiaanstals** [comment]
Issue was a .DS_store file in the keys directory - for anyone else that gets stuck

**Comment by tiaanstals** [comment]
Turns out this is not the problem. This is a persistent issue I encounter once I run my built java application using jetty runner

**Comment by tiaanstals** [comment]
Here is some more output coming from the token.io package

```
2019-12-20 00:37:01,393 ERROR Host=i-0e0b2504b1406d2f7 [grpc-timer-0hread] stake_tid= userId= StdOutLogger 3432 [grpc-timer-0] WARN io.token.proto.gateway.GatewayService.client - RETRY: GetMember, backoff=0, req=(member_id: "m:4KhGUvGq6KjiTA9Q4GcshMeTv2g4:5zKtXEAq"), Metadata(token-realm=Token,token-scheme=Token-Ed25519-SHA512,token-key-id=USrczCPH0Sbx-cq8,token-signature=ejbT2sByS7DgGYmlOSkZLUFIo4j2CW5MJcMz41VF4TplLPQjub5-I3p0fJdEXTRuC4RG6UBeJxl2qTkH8QRrAQ,token-created-at-ms=1576802218726,token-member-id=m:4KhGUvGq6KjiTA9Q4GcshMeTv2g4:5zKtXEAq,token-security-metadata=e30=,token-dev-key=4qY7lqQw8NOl9gng0ZHgT4xdiDqxqoGVutuZwrUYQsI,token-sdk=java-tpp,token-sdk-version=2.7.5,token-trace-id=lT2KIMorPrXdNI7m,grpc-accept-encoding=gzip)

2019-12-20 00:37:01,399 ERROR Host=i-0e0b2504b1406d2f7 [rpc-client-1hread] stake_tid= userId= StdOutLogger 3438 [rpc-client-1] ERROR io.token.proto.gateway.GatewayService.client - ERROR: GetMember res=(UNAVAILABLE, io exception), null

2019-12-20 00:37:01,400 ERROR Host=i-0e0b2504b1406d2f7 [rpc-client-1hread] stake_tid= userId= StdOutLogger javax.net.ssl.SSLHandshakeException: General OpenSslEngine problem
```

**Comment by tiaanstals** [comment]
Trying to load a member
```
2019-12-20 00:22:05,163 ERROR Host=i-0e0b2504b1406d2f7 [grpc-timer-0hread] stake_tid= userId= StdOutLogger 2166 [grpc-timer-0] WARN io.token.proto.gateway.GatewayService.client - RETRY: GetMember, backoff=18, req=(member_id: "m:4KhGUvGq6KjiTA9Q4GcshMeTv2g4:5zKtXEAq"), Metadata(token-realm=Token,token-scheme=Token-Ed25519-SHA512,token-key-id=USrczCPH0Sbx-cq8,token-signature=5FeaUXODKU_b7gBmFyLAvAbSFxNkIwYDRuHMm7jFUN4J57quwuVS2cr0YkeQ8bbrt9QiWqfTO7iVRUcJVC5hAA,token-created-at-ms=1576801323747,token-member-id=m:4KhGUvGq6KjiTA9Q4GcshMeTv2g4:5zKtXEAq,token-security-metadata=e30=,token-dev-key=4qY7lqQw8NOl9gng0ZHgT4xdiDqxqoGVutuZwrUYQsI,token-sdk=java-tpp,token-sdk-version=2.7.5,token-trace-id=Gg0AQFjxqIFZ0YVy,grpc-accept-encoding=gzip)

2019-12-20 00:22:05,164 ERROR Host=i-0e0b2504b1406d2f7 [rpc-client-1hread] stake_tid= userId= StdOutLogger 2167 [rpc-client-1] ERROR io.token.proto.gateway.GatewayService.client - ERROR: GetMember res=(UNAVAILABLE, io exception), null
```
